config/routes.rb
EmberWithCoffee::Application.routes.draw do
  resources :articles do
    resources :words, :only => [:index]
  end
  resources :words, :except => [:index]

  root :to => 'demo#index'
  match 'dictionary/word/:name' => 'demo#dictionary'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title, :id
  has_many :words
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :article_id, :desc, :kana, :kanji, :position
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  if Rails.env.production?
    http_basic_authenticate_with :name => ENV['APP_USER'] || 'afs234aa', :password =>  ENV['APP_PASSWORD'] || '234fsd234rq2da'
    force_ssl
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/demo_controller.rb
require 'kanji_dictionary'
class DemoController < ApplicationController
  def index
    Rails.logger.debug "DEBUG: Demo/index"
    @article = Article.last
  end
  def dictionary
    dictionary = KanjiDictionary.new
    result = dictionary.search(params[:name])
    Rails.logger.debug "Dictionary said: #{result}"
    render :json => result.sort { |a,b| 
      a[1].length <=> b[1].length 
    }.each_with_index.select{ |r,i| 
        i < 5 }.map(&:first)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_filter :find_article, :only => :index
  # GET /words
  # GET /words.json
  def index
    position = params[:position].to_i || 0
    range = (position..(position+12)) 
    @words = Word.where(:article_id => @article.id, :position => range).all if @article

    respond_to do |format|
      format.html # index.html.erb

      format.json { 
        Rails.logger.debug "WORD: #{@words.to_json}"
        render json: @words 
      }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])
    Rails.logger.debug @word.to_json
    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
  private
  def find_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/demo/index.html.haml
- content_for :title, 'Demo Ember.js Application' 
.container-fluid
  .row
    .span6
      %script(type="text/x-handlebars")
        {{view App.ResultView class="row"}}
    .span1#words
      %script(type="text/x-handlebars")
        {{#view App.WordsView wordsBinding="App.WordsController" class="nav nav-pills" tagName="ul" }}
        {{#each words }}
        <li class='active'><a href='#' {{bindAttr id="id"}}>{{display}}</a></li>
        {{/each}}
        {{/view}}
    .span5#article
      %script(type="text/x-handlebars")
        
        {{view App.ArticleView class="row"}}
    .span6
      %script(type="text/x-handlebars")
        {{view App.ArticlesList}}
        / - @article.content.split('').each_with_index do |l,index|
        /   %span{:class=>"#{index}"}
        /     = l.strip

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EmberWithCoffee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kanji %><br />
    <%= f.text_field :kanji %>
  </div>
  <div class="field">
    <%= f.label :kana %><br />
    <%= f.text_field :kana %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.text_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th>Kanji</th>
    <th>Kana</th>
    <th>Desc</th>
    <th>Article</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.kanji %></td>
    <td><%= word.kana %></td>
    <td><%= word.desc %></td>
    <td><%= word.article_id %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kanji:</b>
  <%= @word.kanji %>
</p>

<p>
  <b>Kana:</b>
  <%= @word.kana %>
</p>

<p>
  <b>Desc:</b>
  <%= @word.desc %>
</p>

<p>
  <b>Article:</b>
  <%= @word.article_id %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>